# Generated by Django 1.11.29 on 2021-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentry", "0184_copy_useroptions_to_notificationsettings_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="state",
            field=models.PositiveIntegerField(
                choices=[(0, "Active Member"), (1, "Invited"), (2, "Inactive")], default=0
            ),
        ),
    ]
